In [1]:
import sqlite3
import pandas as pd 
import numpy as np
from sqlalchemy import create_engine

## Top 5 funds by AUM

In [3]:
engine = create_engine("sqlite:///../bluestock_mf.db")
conn = sqlite3.connect("../bluestock_mf.db")
cursor = conn.cursor()
query = """
SELECT
    df.scheme_name,
    fp.aum_crore
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
ORDER BY fp.aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

                                         scheme_name  aum_crore
0  Mirae Asset Emerging Bluechip Fund - Regular -...    49046.0
1      Kotak Emerging Equity Fund - Regular - Growth    47469.0
2     Nippon India Small Cap Fund - Regular - Growth    43630.0
3         DSP Top 100 Equity Fund - Regular - Growth    41828.0
4                UTI Mid Cap Fund - Regular - Growth    41728.0

## Average Nav per month

In [5]:
query = """
SELECT
    dd.year,
    dd.month,
    ROUND(AVG(fn.nav),2) AS average_nav
FROM fact_nav fn
JOIN dim_date dd
ON fn.date_id = dd.date_id
GROUP BY dd.year, dd.month
ORDER BY dd.year, dd.month;
"""
pd.read_sql(query, engine)

    year  month  average_nav
0   2022      1       207.05
1   2022      2       207.72
2   2022      3       209.69
3   2022      4       211.79
4   2022      5       212.73
5   2022      6       213.86
6   2022      7       213.95
7   2022      8       215.70
8   2022      9       218.47
9   2022     10       219.53
10  2022     11       223.51
11  2022     12       226.75
12  2023      1       230.62
13  2023      2       233.83
14  2023      3       237.90
15  2023      4       240.56
16  2023      5       241.89
17  2023      6       244.56
18  2023      7       245.84
19  2023      8       247.60
20  2023      9       251.84
21  2023     10       255.53
22  2023     11       258.34
23  2023     12       262.02
24  2024      1       264.59
25  2024      2       266.26
26  2024      3       269.64
27  2024      4       271.26
28  2024      5       273.38
29  2024      6       275.39
30  2024      7       279.10
31  2024      8       279.75
32  2024      9       281.07
33  2024     10       282.11
34  2024     11       285.27
35  2024     12       285.23
36  2025      1       287.91
37  2025      2       291.50
38  2025      3       296.13
39  2025      4       299.40
40  2025      5       303.88
41  2025      6       306.87
42  2025      7       309.71
43  2025      8       313.14
44  2025      9       316.12
45  2025     10       321.35
46  2025     11       325.67
47  2025     12       331.77
48  2026      1       337.07
49  2026      2       342.03
50  2026      3       347.21
51  2026      4       355.03
52  2026      5       356.99

## Total transaction by state

In [6]:
query = """
SELECT
    state,
    COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY state
ORDER BY total_transactions DESC;
"""
pd.read_sql(query,engine)

             state  total_transactions
0           Punjab                2965
1   Madhya Pradesh                2931
2       Tamil Nadu                2806
3          Gujarat                2780
4      West Bengal                2748
5          Haryana                2736
6        Telangana                2718
7    Uttar Pradesh                2695
8            Delhi                2677
9        Karnataka                2621
10       Rajasthan                2577
11     Maharashtra                2524

## Total Transaction Amount by State

In [7]:
query = """SELECT
    state,
    ROUND(SUM(amount_inr),2) AS total_amount
FROM fact_transactions
GROUP BY state
ORDER BY total_amount DESC;

"""
pd.read_sql(query,engine)

             state  total_amount
0           Punjab   315780459.0
1       Tamil Nadu   315177237.0
2   Madhya Pradesh   308312493.0
3        Rajasthan   298645822.0
4          Gujarat   298358940.0
5      West Bengal   297182514.0
6        Telangana   290219284.0
7            Delhi   289633404.0
8    Uttar Pradesh   285368873.0
9          Haryana   279634354.0
10       Karnataka   273753570.0
11     Maharashtra   269513480.0

## Funds with Expense Ratio less than 1%

In [8]:
query = """SELECT
    df.scheme_name,
    fp.expense_ratio_pct
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
WHERE fp.expense_ratio_pct < 1
ORDER BY fp.expense_ratio_pct;
"""
pd.read_sql(query,engine)

                                          scheme_name  expense_ratio_pct
0   Nippon India Gilt Securities Fund - Regular - ...               0.55
1        HDFC Short Term Debt Fund - Regular - Growth               0.56
2                Kotak Liquid Fund - Regular - Growth               0.60
3            SBI Bluechip Fund - Direct Plan - Growth               0.66
4           SBI Small Cap Fund - Direct Plan - Growth               0.72
5       Nippon India Large Cap Fund - Direct - Growth               0.72
6            ICICI Pru Liquid Fund - Regular - Growth               0.74
7                Axis Bluechip Fund - Direct - Growth               0.75
8        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
9   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78
10                ABSL Liquid Fund - Regular - Growth               0.79
11          ICICI Pru Bluechip Fund - Direct - Growth               0.80
12                     Nippon India ETF Nifty 50 BeES               0.89
13           HDFC Top 100 Fund - Direct Plan - Growth               0.92

## Top 10 Funds by Sharpe Ratio

In [9]:
query = """
SELECT
    df.scheme_name,
    fp.sharpe_ratio
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
ORDER BY fp.sharpe_ratio DESC
LIMIT 10;
"""
pd.read_sql(query,engine)

                                         scheme_name  sharpe_ratio
0           ICICI Pru Liquid Fund - Regular - Growth          7.68
1               Kotak Liquid Fund - Regular - Growth          6.18
2                ABSL Liquid Fund - Regular - Growth          5.14
3       HDFC Short Term Debt Fund - Regular - Growth          1.84
4       SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
5  Nippon India Gilt Securities Fund - Regular - ...          1.33
6          HDFC Top 100 Fund - Regular Plan - Growth          1.06
7      Mirae Asset Large Cap Fund - Regular - Growth          1.06
8          ICICI Pru Bluechip Fund - Direct - Growth          1.03
9     Nippon India Large Cap Fund - Regular - Growth          1.00

## Average 3-Year Return by Category

In [10]:
query = """SELECT
    df.category,
    ROUND(AVG(fp.return_3yr_pct),2) AS avg_return_3yr
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
GROUP BY df.category
ORDER BY avg_return_3yr DESC;"""
pd.read_sql(query,engine)

  category  avg_return_3yr
0   Equity           15.46
1     Debt            6.29

## Transactions by Payment Mode

In [11]:
query = """SELECT
    payment_mode,
    COUNT(*) AS total_transactions,
    ROUND(SUM(amount_inr),2) AS total_amount
FROM fact_transactions
GROUP BY payment_mode
ORDER BY total_amount DESC;"""
pd.read_sql(query,engine)

  payment_mode  total_transactions  total_amount
0  Net Banking                8250   893492623.0
1       Cheque                8228   892219218.0
2          UPI                8154   888241021.0
3      Mandate                8146   847627568.0

## Number of Funds in each Risk Category

In [12]:
query = """SELECT
    risk_category,
    COUNT(*) AS total_funds
FROM dim_fund
GROUP BY risk_category
ORDER BY total_funds DESC;
"""
pd.read_sql(query,engine)

     risk_category  total_funds
0         Moderate           16
1             High            8
2        Very High            6
3              Low            6
4  Moderately High            4

## Average NAV by Fund House

In [13]:
query = """SELECT
    df.fund_house,
    ROUND(AVG(fn.nav),2) AS average_nav
FROM fact_nav fn
JOIN dim_fund df
ON fn.fund_id = df.fund_id
GROUP BY df.fund_house
ORDER BY average_nav DESC;"""
pd.read_sql(query,engine)

                 fund_house  average_nav
0         Kotak Mahindra MF      1056.55
1          HDFC Mutual Fund       344.29
2  Aditya Birla Sun Life MF       284.36
3           DSP Mutual Fund       246.23
4       ICICI Prudential MF       216.35
5           UTI Mutual Fund       171.67
6            Mirae Asset MF       112.89
7           SBI Mutual Fund       103.40
8           Nippon India MF       100.09
9          Axis Mutual Fund        72.23